version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: 6467f5a836603c2af14c16042489ac4ad17a47d2
        databases:
          default:
            connector: postgres
            host: ${DATABASE_HOST}
            database: ${DATABASE}
            ssl: true
            user: ${DATABASE_USER}
            password: ${DATABASE_PASS}
            rawAccess: true
            port: '5432'
            migrations: true